### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by swapps** [itaybia/androidHarmony#2]
Hi,

i'm trying to use your code in my app but i'm getting this error when i try to connect.

01-01 19:24:06.331: E/JabberSmackAPI(12652): login connect failed. 192.168.1.20:7895 Exception: XMPPError connecting to 192.168.1.20:7895.; 
01-01 19:24:06.331: W/System.err(12652): 192.168.1.20:7895 Exception: XMPPError connecting to 192.168.1.20:7895.; : remote-server-error(502)
01-01 19:24:06.332: W/System.err(12652):   -- caused by: XMPPError connecting to 192.168.1.20:7895.: remote-server-error(502) XMPPError connecting to 192.168.1.20:7895.
01-01 19:24:06.332: W/System.err(12652):   -- caused by: java.net.ConnectException: failed to connect to /192.168.1.20 (port 7895): connect failed: ECONNREFUSED (Connection refused)
01-01 19:24:06.362: W/System.err(12652):    at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:601)
01-01 19:24:06.362: W/System.err(12652):    at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1021)
01-01 19:24:06.362: W/System.err(12652):    at com.preiss.swapps.harmony.api.JabberSmackAPI.login(JabberSmackAPI.java:51)
01-01 19:24:06.362: W/System.err(12652):    at com.preiss.swapps.harmony.api.Authentication$GuestSessionTokenTask.doInBackground(Authentication.java:192)
01-01 19:24:06.362: W/System.err(12652):    at com.preiss.swapps.harmony.api.Authentication$GuestSessionTokenTask.doInBackground(Authentication.java:165)
01-01 19:24:06.362: W/System.err(12652): java.net.ConnectException: failed to connect to /192.168.1.20 (port 7895): connect failed: ECONNREFUSED (Connection refused)
01-01 19:24:06.376: W/System.err(12652):    at libcore.io.IoBridge.connect(IoBridge.java:128)
01-01 19:24:06.376: W/System.err(12652):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
01-01 19:24:06.376: W/System.err(12652):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
01-01 19:24:06.376: W/System.err(12652):    at java.net.Socket.connect(Socket.java:887)
01-01 19:24:06.376: W/System.err(12652):    at java.net.Socket.connect(Socket.java:830)
01-01 19:24:06.376: W/System.err(12652):    at org.jivesoftware.smack.proxy.DirectSocketFactory.createSocket(DirectSocketFactory.java:48)
01-01 19:24:06.376: W/System.err(12652):    at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:566)
01-01 19:24:06.376: W/System.err(12652):    at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1021)
01-01 19:24:06.376: W/System.err(12652):    at com.preiss.swapps.harmony.api.JabberSmackAPI.login(JabberSmackAPI.java:51)
01-01 19:24:06.376: W/System.err(12652):    at com.preiss.swapps.harmony.api.Authentication$GuestSessionTokenTask.doInBackground(Authentication.java:192)
01-01 19:24:06.376: W/System.err(12652):    at com.preiss.swapps.harmony.api.Authentication$GuestSessionTokenTask.doInBackground(Authentication.java:165)

Do you have any ideas what might be wrong ?

**Comment by itaybia** [comment]
it's been a while since i looked into this. i just tested my client and it works with my harmony ultimate on the latest firmware. so it isn't something related to changes since i wrote the code.
did you configure the correct network? (using wifi/3g, what is the IP/dns name)
